# Generated by Django 4.1.4 on 2023-01-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_stripe_product_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='аvilability',
            new_name='presence',
        ),
    ]
